# Generated by Django 5.2.7 on 2026-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerorder',
            name='delivery_method',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='farmerorder',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
