# Generated by Django 5.2.7 on 2026-03-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_payment_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerorder',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
