# Generated by Django 5.2.7 on 2026-02-07 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('direccion_completa', models.CharField(max_length=255)),
                ('descripcion_perfil', models.CharField(blank=True, max_length=40, null=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=100)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
