# Generated by Django 5.2.7 on 2026-02-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='codigo_reset',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='fecha_expiracion_codigo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
