# Generated by Django 5.2.7 on 2026-03-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_register_descripcion_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='admin_code_validated',
            field=models.BooleanField(default=False),
        ),
    ]
