# Generated by Django 5.2.7 on 2026-03-03 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tiendas', '0002_promote_shop_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('Frutas', 'Frutas'), ('Vegetales', 'Vegetales'), ('Lácteos', 'Lácteos'), ('Carne', 'Carne'), ('Granos', 'Granos'), ('Otros', 'Otros')], max_length=20)),
                ('tipo_otro', models.CharField(blank=True, max_length=60)),
                ('unidad', models.CharField(choices=[('Libra', 'Libra'), ('Kilo', 'Kilo'), ('Arroba', 'Arroba'), ('Litro', 'Litro')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField()),
                ('garantia', models.CharField(max_length=120)),
                ('metodo_pago', models.CharField(choices=[('contado', 'Pago de contado'), ('entrega', 'Pago contra entrega'), ('transferencia', 'Transferencia')], max_length=20)),
                ('metodo_entrega', models.CharField(choices=[('domicilio', 'Envío a domicilio'), ('tienda', 'Recogido en tienda'), ('cita', 'Entrega bajo cita')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Tiendas.shop')),
            ],
            options={
                'db_table': 'productos_product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Productos.product')),
            ],
            options={
                'db_table': 'productos_product_image',
            },
        ),
    ]
