# Generated by Django 5.2.7 on 2026-03-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='metodo_entrega',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metodo_pago',
        ),
    ]
