# Generated by Django 5.2.7 on 2026-03-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_remove_metodo_pago_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disabled_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
