# Generated by Django 5.2.7 on 2026-03-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_product_product_price_non_negative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidad',
            field=models.CharField(choices=[('Libra', 'Libra'), ('Kilo', 'Kilo'), ('Arroba', 'Arroba'), ('Litro', 'Litro'), ('Unidad', 'Unidad')], max_length=10),
        ),
    ]
