# Lista de departamentos y municipios válidos para Colombia (ejemplo)
DEPARTAMENTOS_MUNICIPIOS = {
    'Amazonas': ['Leticia', 'Puerto Nariño'],
    'Antioquia': ['Medellín', 'Bello', 'Envigado', 'Itagüí'],
    'Atlántico': ['Barranquilla', 'Soledad'],
    'Bogotá D.C.': ['Bogotá'],
    'Bolívar': ['Cartagena', 'Magangué'],
    'Boyacá': ['Tunja', 'Duitama'],
    'Caldas': ['Manizales', 'Villamaría'],
    'Caquetá': ['Florencia'],
    'Cauca': ['Popayán'],
    'Cesar': ['Valledupar'],
    'Córdoba': ['Montería'],
    'Cundinamarca': ['Soacha', 'Zipaquirá'],
    'Chocó': ['Quibdó'],
    'Huila': ['Neiva'],
    'La Guajira': ['Riohacha'],
    'Magdalena': ['Santa Marta'],
    'Meta': ['Villavicencio'],
    'Nariño': ['Pasto'],
    'Norte de Santander': ['Cúcuta'],
    'Putumayo': ['Mocoa'],
    'Quindío': ['Armenia'],
    'Risaralda': ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal'],
    'Santander': ['Bucaramanga'],
    'Sucre': ['Sincelejo'],
    'Tolima': ['Ibagué'],
    'Valle del Cauca': ['Cali', 'Palmira', 'Buenaventura'],
    'Vaupés': ['Mitú'],
    'Vichada': ['Puerto Carreño'],
}
