# Generated by Django 5.2.7 on 2026-02-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_rename_sitio_web_shop_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.shop',),
        ),
    ]
