# Generated by Django 5.2.7 on 2026-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0002_promote_shop_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='punto_fisico',
            field=models.BooleanField(default=True),
        ),
    ]
