# Generated by Django 5.2.7 on 2026-03-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendas', '0003_shop_punto_fisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
