# Generated by Django 5.2.7 on 2026-03-14 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0002_farmerreply'),
        ('usuarios', '0006_register_admin_code_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToUserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('enviado', models.BooleanField(default=False)),
                ('leido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_admin', to='usuarios.register')),
            ],
        ),
    ]
