# Generated by Django 5.2.7 on 2026-03-19 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0003_admintousermessage'),
        ('Productos', '0004_product_disabled_by_admin'),
        ('usuarios', '0006_register_admin_code_validated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('product_reactivation', 'Solicitud de activacion de producto')], max_length=40)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='Productos.product')),
                ('sender_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications_sent', to='usuarios.register')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensajes_admin_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
