# Generated by Django 5.2.7 on 2026-03-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajes', '0004_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('product_reactivation', 'Solicitud de activacion de producto'), ('blocked_login_attempt', 'Intento de inicio de sesion de usuario bloqueado')], max_length=40),
        ),
    ]
